#!/usr/bin/env node
// Walk patterns/** and emit frontend/src/generated/patterns.js — a single
// ES module that exports an array of fully-hydrated pattern objects:
//
//   { id, track, group, sequence, title, gof_name, verdict, rust_alternative,
//     hints, markdown, codeFiles: [{ filename, source, playground }] }
//
// Run as a prebuild step (see frontend/package.json).

import { readdir, readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

// gray-matter is a CommonJS package installed under frontend/node_modules.
// Resolve it explicitly so this script runs whether invoked from the repo
// root or from frontend/ via npm run.
const require = createRequire(
  new URL('../frontend/package.json', import.meta.url),
);
const matter = require('gray-matter');

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..');
const patternsRoot = join(repoRoot, 'patterns');
const outFile = join(repoRoot, 'frontend', 'src', 'generated', 'patterns.js');

async function* walkPatterns(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const sub = join(dir, entry.name);
    const indexPath = join(sub, 'index.md');
    if (existsSync(indexPath)) {
      yield { dir: sub, indexPath };
    } else {
      yield* walkPatterns(sub);
    }
  }
}

// Build a shareable Rust Playground URL with the source embedded in the
// query string. The Playground accepts a `code` param containing
// URL-encoded Rust. This is simpler than gist-backed links and keeps the
// source of truth in the repo. Long files may produce long URLs — the
// 8 KB ceiling is fine for the small teaching snippets we ship.
function playgroundUrl(source) {
  const encoded = encodeURIComponent(source);
  return `https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=${encoded}`;
}

async function loadCodeFiles(patternDir, playgroundLinks) {
  const codeDir = join(patternDir, 'code');
  if (!existsSync(codeDir)) return [];
  const files = await readdir(codeDir);
  files.sort();
  const results = [];
  for (const f of files) {
    if (!f.endsWith('.rs')) continue;
    const full = join(codeDir, f);
    const st = await stat(full);
    if (!st.isFile()) continue;
    const source = await readFile(full, 'utf8');
    const key = f.replace(/\.rs$/, '');
    // Prefer an explicit URL from frontmatter if it actually carries a
    // `code=` or `gist=` payload (useful for long-lived curated shares);
    // otherwise synthesize one from the source itself so every snippet
    // has a working "Open in Playground" button.
    const override = (playgroundLinks ?? {})[key];
    const hasPayload =
      typeof override === 'string' &&
      (override.includes('code=') || override.includes('gist='));
    const playground = hasPayload ? override : playgroundUrl(source);
    results.push({
      filename: f,
      key,
      source,
      playground,
    });
  }
  return results;
}

async function build() {
  const patterns = [];
  for await (const { dir, indexPath } of walkPatterns(patternsRoot)) {
    const raw = await readFile(indexPath, 'utf8');
    const parsed = matter(raw);
    const { data, content } = parsed;

    const codeFiles = await loadCodeFiles(dir, data.playground_links);

    patterns.push({
      id: data.id ?? relative(patternsRoot, dir).replace(/[\\/]/g, '-'),
      track: data.track ?? 'gof',
      group: data.group ?? null,
      sequence: data.sequence ?? 0,
      title: data.title ?? data.id ?? 'Untitled',
      gof_name: data.gof_name ?? null,
      verdict: data.verdict ?? 'use',
      rust_alternative: data.rust_alternative ?? null,
      hints: data.hints ?? [],
      playground_links: data.playground_links ?? {},
      markdown: content,
      codeFiles,
      sourcePath: relative(repoRoot, indexPath),
    });
  }

  patterns.sort((a, b) => {
    if (a.track !== b.track) return a.track.localeCompare(b.track);
    if (a.group !== b.group) return (a.group ?? '').localeCompare(b.group ?? '');
    return (a.sequence ?? 0) - (b.sequence ?? 0);
  });

  const header = `// AUTO-GENERATED by scripts/build-index.mjs. Do not edit by hand.\n// Regenerate with: npm run reindex\n`;
  const body = `export default ${JSON.stringify(patterns, null, 2)};\n`;

  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, header + body, 'utf8');

  console.log(
    `[build-index] wrote ${patterns.length} pattern${patterns.length === 1 ? '' : 's'} → ${relative(repoRoot, outFile)}`,
  );
}

build().catch((err) => {
  console.error('[build-index] failed:', err);
  process.exit(1);
});
